# Generated by Django 3.0.7 on 2020-06-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Наименование')),
                ('has_an_expiration_date', models.BooleanField(default=False, verbose_name='Имеет срок действия')),
                ('has_a_series', models.BooleanField(default=False, verbose_name='Имеет серию')),
            ],
        ),
        migrations.CreateModel(
            name='Lost_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=256, unique=True, verbose_name='Идентификатор')),
                ('document_series', models.CharField(blank=True, max_length=256, verbose_name='Серия документа')),
                ('document_number', models.CharField(blank=True, max_length=256, verbose_name='Номер документа')),
                ('status', models.CharField(blank=True, max_length=256, verbose_name='Статус')),
                ('event_date', models.CharField(blank=True, max_length=256, verbose_name='Дата события')),
                ('date_of_recording', models.CharField(blank=True, max_length=256, verbose_name='Дата записи')),
                ('registration_authority', models.CharField(blank=True, max_length=256, verbose_name='Орган регистрации события')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_type', to='main.Document_type', verbose_name='Тип документа')),
            ],
        ),
    ]
