# Generated by Django 3.0.7 on 2020-06-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_documents',
            old_name='department_type',
            new_name='document_type',
        ),
    ]
